# Generated by Django 5.2 on 2025-05-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_image', models.URLField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.URLField()),
                ('stand_side', models.CharField(max_length=1)),
                ('pitch_type', models.CharField(max_length=2)),
                ('velocity_range', models.CharField(max_length=20)),
                ('usage_rate', models.CharField(max_length=10)),
                ('zone_rate', models.CharField(max_length=10)),
                ('avg_spin_rate', models.FloatField()),
                ('avg_horz_break', models.FloatField()),
                ('avg_induced_vert_break', models.FloatField()),
                ('arm_angle', models.FloatField()),
                ('throws', models.CharField(max_length=1)),
                ('heatmap_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pitchers.pitcher')),
            ],
            options={
                'unique_together': {('user', 'pitcher')},
            },
        ),
    ]
